version: "3.8"

services:
  pfra-notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
      - /mnt/c/Users/sputnam/OneDrive - Dewberry/Projects/FFRD/Cedar_Rapids:/Cedar_Rapids
