version: "3.8"

services:
  pfra-notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
      - /mnt/c/Users/sputnam/Documents/Projects/PFRA/PFRA_Production/Pluvial/CedarRapids/Outputs:/Outputs